# **Numpy介紹**
* NumPy支援高維度陣列與矩陣運算，此外也針對陣列運算提供大量的數學函式函式庫。
* Numpy底層以C和Fortran語言實作，所以能快速操作多重維度的陣列。當 Python 處理龐大資料時，其原生 list 效能表現並不理想(但可以動態存異質資料)，而 Numpy 具備平行處理的能力，可以將操作動作一次套用在大型陣列上。
* Python其餘重量級的資料科學相關套件(例如：Pandas、SciPy、Scikit-learn)都幾乎是奠基在Numpy的基礎上。

For this tutorial, we start by importing the package.

In [17]:
import numpy as np

### **Note 1. 陣列宣告** 
Numpy的重點在於陣列的操作，其所有功能特色建築在同質且多重維度的ndarra(N-dimensional array)上。ndarray的關鍵屬性是維度(ndim)、形狀(shape)和數值類型(dtype)。一般我們稱一維陣列為 vector 而二維陣列為 matrix。


In [18]:
np1 = np.array([1, 2, 3])
np2 = np.array([3, 4, 5])
print(np1.ndim, np1.shape, np1.dtype)

1 (3,) int32


### **Note 2. 改變陣列維度**

In [19]:
np3 = np.array([1, 2, 3, 4, 5, 6])     # 1D array np3[6]
print(np3.ndim, np3.shape, np3.dtype)  # 2 (2, 3) int64
np4 = np3.reshape([2, 3])        # 2D array  np3[2][3]
print()
print(np4.ndim, np4.shape, np4.dtype)  # 2 (2, 3) int64


1 (6,) int32

2 (2, 3) int32


### **Note 3. 改變陣列型別(bool、int、float、string)**
* bool 可以包含 True、False 
* int 可以包含 int16、int32、int64
* bits表示數字 
* float 可以包含 16、32、64 表示小數點後幾位
* string 可以是 string、unicode
* nan 則表示遺失值

In [20]:
np3=np3.astype('float32')   # 資料型別轉換:int64-->float32 
print(np3.dtype)

float32


### **Note 4. 建立填滿0或1的Numpy陣列、建立無初始值的Numpy陣列**

In [21]:
np1 = np.zeros([2, 3])    # array([[ 0.,  0.,  0.], [ 0.,  0.,  0.]])
np2 = np.ones([2, 3])     # array([[ 1.,  1.,  1.], [ 1.,  1.,  1.]])
np3 = np.empty([2, 3])    # 無初始值的陣列
print("np1=>{0}".format(np1))
print("np2=>{0}".format(np2))
print("np3=>{0}".format(np3))


np1=>[[0. 0. 0.]
 [0. 0. 0.]]
np2=>[[1. 1. 1.]
 [1. 1. 1.]]
np3=>[[0. 0. 0.]
 [0. 0. 0.]]


### **Note 5. 建立亂數值的陣列**

In [22]:
b1 = np.random.random([10, 3])
print("b1=>", b1)

b1=> [[0.48706799 0.19359376 0.21828895]
 [0.57971935 0.08835831 0.47408326]
 [0.79616812 0.15822962 0.49451858]
 [0.34979353 0.1914942  0.35074616]
 [0.04764848 0.2210143  0.83552385]
 [0.85844288 0.99633836 0.58976168]
 [0.22192524 0.59895717 0.31068962]
 [0.68012862 0.30388454 0.83952804]
 [0.99995237 0.33778232 0.94311528]
 [0.51586265 0.15290769 0.87850692]]


### **Note 6. 建立連續數值的陣列**
np.arange(起始值, 結束值, 步幅, 資料型別)：產生一維陣列，和np.array()的差別在於arange擁有較大彈性，元素數值是自動化產生，步幅決定每隔多少數值產生一個元素(等差)。




In [23]:
r1 = np.arange(25, 30, .5)
print("r1=>", r1)

r1=> [25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


### **Note 7. 陣列資料訪問**

numpy陣列與python的列表有些相似，也可以利用切片對陣列進行訪問

In [24]:
data = np.array([[1, 2, 3, 4, 5],
                 [3, 4, 6, 7, 9],
                 [2, 2, 5, 6, 9],
                 [5, 9, 5, 6, 1]])
print("data[1,3]=>", data[1, 3])


data[1,3]=> 7


In [25]:
print("data[1:3]=>\n", data[1:3])

data[1:3]=>
 [[3 4 6 7 9]
 [2 2 5 6 9]]


In [26]:
print("data[1:3,2:4]=>\n", data[1:3, 2:4])

data[1:3,2:4]=>
 [[6 7]
 [5 6]]


In [27]:
print("data[:,1:3]=>\n", data[:, 1:3])

data[:,1:3]=>
 [[2 3]
 [4 6]
 [2 5]
 [9 5]]


### **In-class Exercise**  
建立一numpy矩陣
```
 [[1,2,3,4,5,6],
 [7,8,9,10,11,12],
 [13,14,15,16,17,18],
 [19,20,21,22,23,24]]
```
使用”print”
* 輸出陣列[0,3]、[2,4]元素
* 輸出陣列中1-2列中的元素
* 輸出陣列中0-2列與2-3行之間交叉的元素
* 輸出陣列中2-4列的元素
* 輸出陣列中0-1行的元素
  

In [28]:
#TODO
arr =  np.array([np.arange(1, 25, 1)]).reshape([4, 6])
print(arr, "\n")
print(arr[0, 3], arr[2, 4], "\n")
print(arr[1: 3], "\n")
print(arr[0: 3, 2: 4], "\n")
print(arr[2: 5], "\n")
print(arr[:, 0: 2], "\n")

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] 

4 17 

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] 

[[ 3  4]
 [ 9 10]
 [15 16]] 

[[13 14 15 16 17 18]
 [19 20 21 22 23 24]] 

[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]] 



### **Note8. 矩陣運算**

**A.基本運算**

矩陣(matrix)等同於是維度為2的陣列。
`numpy` 提供 `numpy.matrix` 進行矩陣操作，但同樣的操作也可以直接進行在 `numpy.ndarray` 之上。

|函數|意義|
|-|-|
|`numpy.matrix`|創造矩陣|
|`numpy.transpose`|矩陣轉置|
|`numpy.dot`|矩陣乘法|
|`numpy.diag`|取出對角線|

In [29]:
# 基本運算
import numpy as np
# 宣告matrix變數
mat1 = np.matrix([[0, 10, 20],
                  [30, 40, 50]])

# 輸出矩陣mat1
print("Matrix 1=>\n", mat1)
print()

# 輸出矩陣mat1轉置後的結果
print("The transpose of matrix 1=>", np.transpose(mat1))
print()

# 宣告matrix變數
mat2 = np.matrix(np.arange(12).reshape(3, 4))

# 輸出矩陣mat2
print("Matrix 2=>\n", mat2)
print()

# 輸出矩陣mat1乘上矩陣mat2後的結果
print("The multiplication of matrix 1 and matrix 2", np.dot(mat1, mat2))
print()

# 輸出矩陣mat2的對角線數值
print("Diagonal entries of matrix 2=>", np.diag(mat2))
print()

Matrix 1=>
 [[ 0 10 20]
 [30 40 50]]

The transpose of matrix 1=> [[ 0 30]
 [10 40]
 [20 50]]

Matrix 2=>
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

The multiplication of matrix 1 and matrix 2 [[200 230 260 290]
 [560 680 800 920]]

Diagonal entries of matrix 2=> [ 0  5 10]



**B.進階運算**

使用 `numpy.linalg` 進行線性代數中常見的計算。

|函數|意義|
|-|-|
|`numpy.linalg.inv`|反矩陣（Inverse Matrix）|
|`numpy.linalg.eig`|特徵值與特徵向量矩陣（Eigenvalues & Eigenvectors）|
|`numpy.linalg.eigvals`|特徵值矩陣（Eigenvalues）|
|`numpy.linalg.det`|行列式（Determinant）|
|`numpy.linalg.matrix_rank`|秩（Rank）|

In [30]:
import numpy as np
from numpy.linalg import inv

# 宣告matrix變數
mat3 = np.matrix([[1, 2],
                  [3, 4]])
print("The original matrix=>\n", mat3)
print()

# 計算矩陣mat3的反矩陣
mat3_inv = inv(mat3)

# 輸出矩陣 mat3 的反矩陣
print("The inverse matrix=>\n", mat3_inv)
print()

# 計算矩陣 mat3 與其反矩陣乘積
print("The multiplication of the original and inverse matrices=>\n", mat3.dot(mat3_inv))

The original matrix=>
 [[1 2]
 [3 4]]

The inverse matrix=>
 [[-2.   1. ]
 [ 1.5 -0.5]]

The multiplication of the original and inverse matrices=>
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [31]:
import numpy as np
from numpy.linalg import det, matrix_rank

# 宣告matrix變數
mat5 = np.matrix([[1, 2],
                  [3, 4]])

# 輸出矩陣mat5的行列式
print("matrix determinant=>", det(mat5))

# 輸出矩陣mat5的秩
print("matrix rank=>", matrix_rank(mat5))

matrix determinant=> -2.0000000000000004
matrix rank=> 2


In [32]:
import numpy as np
from numpy.linalg import eig

# 宣告matrix變數
# 宣告matrix變數
mat4 = np.matrix([[1, 3],
                  [3, 5]])
print()

# 計算矩陣mat4的特徵值與特徵向量
mat4_eigval, mat4_eigvec = eig(mat4)

# 輸出矩陣mat4的特徵值
print("eignevalues=>", mat4_eigval)
print()

# 輸出矩陣mat4的特徵向量
print("\neigenvector=>\n", mat4_eigvec)
print()


eignevalues=> [-0.60555128  6.60555128]


eigenvector=>
 [[-0.8816746  -0.47185793]
 [ 0.47185793 -0.8816746 ]]

